apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tetragon
  namespace: monitoring
  labels:
    release: my-kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: tetragon
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tetragon-operator
  namespace: monitoring
  labels:
    release: my-kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/name: tetragon-operator
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics