driver:
  kind: ebpf

falcosidekick:
  enabled: true
  config:
    webhook:
      address: "http://ir-controller.security.svc.cluster.local:8080/webhook"
      minimumpriority: "critical"
    customfields:
      cluster: "kernelsentinel"
