apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: enforce-shells
  labels:
    security.io/mitre-technique-id: "T1059.004"
    security.io/control-type: "enforcement"
  annotations:
    security.io/mitre-tactic: "Execution"
    security.io/mitre-url: "https://attack.mitre.org/techniques/T1059/004/"
    security.io/description: "Blocks interactive shell spawning inside containers"
spec:
  podSelector:
    matchExpressions:
      - key: "k8s:io.kubernetes.pod.namespace"
        operator: NotIn
        values:
          - "security"
          - "falco"
          - "kube-system"
          - "monitoring"
  kprobes:
    - call: "sys_execve"
      syscall: true
      args:
        - index: 0
          type: "string"
      selectors:
        - matchArgs:
            - index: 0
              operator: "Postfix"
              values:
                - "/bash"
                - "/sh"
          matchActions:
            - action: Sigkill