apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: enforce-sensitive-files
  labels:
    security.io/mitre-technique-id: "T1003.008"
    security.io/control-type: "enforcement"
spec:
  podSelector:
    matchExpressions:
      - key: "k8s:io.kubernetes.pod.namespace"
        operator: NotIn
        values:
          - "security"
          - "falco"
          - "kube-system"
          - "monitoring"
  kprobes:
    - call: "security_file_open"
      syscall: false
      args:
        - index: 0
          type: "file"
      selectors:
        - matchArgs:
            - index: 0
              operator: "Postfix"
              values:
                - "/etc/shadow"
                - "/etc/gshadow"
                - "/etc/passwd"
          matchActions:
            - action: Override
              argError: -1