apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: enforce-ptrace
  labels:
    security.io/mitre-technique-id: "T1611"
    security.io/control-type: "enforcement"
  annotations:
    security.io/mitre-tactic: "Privilege Escalation"
    security.io/mitre-url: "https://attack.mitre.org/techniques/T1611/"
    security.io/description: "Blocks container escape via ptrace syscall"
spec:
  podSelector:
    matchExpressions:
      - key: "k8s:io.kubernetes.pod.namespace"
        operator: NotIn
        values:
          - "security"
          - "falco"
          - "kube-system"
          - "monitoring"
  kprobes:
    - call: "sys_ptrace"
      syscall: true
      args:
        - index: 0
          type: "int"
      selectors:
        - matchActions:
            - action: Override
              argError: -1