apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: observe-network
spec:
  podSelector:
    matchExpressions:
      - key: "k8s:io.kubernetes.pod.namespace"
        operator: NotIn
        values:
          - "kube-system"
          - "monitoring"
  kprobes:
    - call: "tcp_connect"
      syscall: false
      args:
        - index: 0
          type: "sock"