# tetragon-policies/observe-exec.yaml
# Logs any time bash, sh, dash, or python is spawned inside any pod
# NO action = observe only
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: observe-exec
spec:
  kprobes:
    - call: "sys_execve"
      syscall: true
      args:
        - index: 0
          type: "string"
      selectors:
        - matchArgs:
            - index: 0
              operator: "Postfix"
              values:
                - "/bash"
                - "/sh"
                - "/dash"
                - "/python"
                - "/python3"